PR.Building4U/PR.Building4U.WebUI/Controllers/CadastroFuncionariosController.cs
using PR.Building4U.Fronteiras.Dtos;
using PR.Building4U.Fronteiras.Executores.AdministrarCargo;
using PR.Building4U.Fronteiras.Executores.AdministrarEstado;
using PR.Building4U.Fronteiras.Executores.AdministrarFuncionario;
using PR.Building4U.Fronteiras.Executores.AdministrarMunicipio;
using PR.Building4U.Fronteiras.Executores.AdministrarObra;
using PR.Building4U.Fronteiras.Executores.AdministrarPais;
using PR.Building4U.WebUI.DataAnnotations;
using PR.Building4U.WebUI.Helper;
using PR.Building4U.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PR.Building4U.WebUI.Controllers
{
    public class CadastroFuncionariosController : BaseController
    {
        [Authorization]
        public ActionResult Index()
        {
            return View();
        }

        [Authorization(new[] { "Index" })]
        public ActionResult Listar(DataTableAjaxPostModel model)
        {
            var requisicao = new ListarFuncionariosRequisicao
            {
                InformacoesLog = this.GetInformacoesLog()
            };
            var executor = this.CriarExecutor<ListarFuncionariosRequisicao, ListarFuncionariosResultado>();
            var resultado = executor.Executar(requisicao);

            var datatable = this.RenderDatatableToView(model, resultado.Funcionarios);

            return Json(datatable, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Incluir(FuncionarioDto funcionario)
        {
            var requisicao = new IncluirFuncionarioRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                ChapaFuncionario = funcionario.ChapaFuncionario,
                NomeFuncionario = funcionario.NomeFuncionario,
                AdmissaoFuncionario = funcionario.AdmissaoFuncionario,
                EmailFuncionario = funcionario.EmailFuncionario,
                TelefoneFuncionario = funcionario.TelefoneFuncionario,
                IdCargo = funcionario.Cargo.IdCargo,
                IdObra = funcionario.Obra.IdObra,
                LogradouroEndereco = funcionario.Endereco.LogradouroEndereco,
                NumeroEndereco = funcionario.Endereco.NumeroEndereco,
                ComplementoEndereco = funcionario.Endereco.ComplementoEndereco,
                CepEndereco = funcionario.Endereco.CepEndereco,
                DistritoEndereco = funcionario.Endereco.DistritoEndereco,
                IdMunicipio = funcionario.Endereco.Municipio.IdMunicipio
            };
            var executor = this.CriarExecutor<IncluirFuncionarioRequisicao, IncluirFuncionarioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Editar(FuncionarioDto funcionario)
        {
            var requisicao = new EditarFuncionarioRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdFuncionario = funcionario.IdFuncionario,
                NomeFuncionario = funcionario.NomeFuncionario,
                EmailFuncionario = funcionario.EmailFuncionario,
                TelefoneFuncionario = funcionario.TelefoneFuncionario,
                IdCargo = funcionario.Cargo.IdCargo,
                IdEndereco = funcionario.Endereco.IdEndereco,
                LogradouroEndereco = funcionario.Endereco.LogradouroEndereco,
                NumeroEndereco = funcionario.Endereco.NumeroEndereco,
                ComplementoEndereco = funcionario.Endereco.ComplementoEndereco,
                CepEndereco = funcionario.Endereco.CepEndereco,
                DistritoEndereco = funcionario.Endereco.DistritoEndereco,
                IdMunicipio = funcionario.Endereco.Municipio.IdMunicipio
            };
            var executor = this.CriarExecutor<EditarFuncionarioRequisicao, EditarFuncionarioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Demitir(int idFuncionario, DateTime demissaoFuncionario)
        {
            var requisicao = new DemitirFuncionarioRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdFuncionario = idFuncionario,
                DemissaoFuncionario = demissaoFuncionario
            };
            var executor = this.CriarExecutor<DemitirFuncionarioRequisicao, DemitirFuncionarioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Editar" })]
        public ActionResult Obter(int idFuncionario)
        {
            var requisicao = new ObterFuncionarioRequisicao()
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdFuncionario = idFuncionario
            };
            var executor = this.CriarExecutor<ObterFuncionarioRequisicao, ObterFuncionarioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarCargos(string codigoOuNome)
        {
            var requisicao = new ListarCargosRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarCargosRequisicao, ListarCargosResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Cargos = resultado.Cargos.OrderBy("NomeCargo asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var cargo in resultado.Cargos)
            {
                selectList.Add(new SelectListItem
                {
                    Value = cargo.IdCargo.ToString(),
                    Text = $"{cargo.NomeCargo} ({cargo.Custo.SiglaCusto})"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir" })]
        public ActionResult ListarObras(string codigoOuNome)
        {
            var requisicao = new ListarObrasRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                CodigoOuNome = codigoOuNome,
                SomenteAtivas = true,
                SomenteObras = false
            };
            var executor = this.CriarExecutor<ListarObrasRequisicao, ListarObrasResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Obras = resultado.Obras.OrderBy("NomeObra asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var obra in resultado.Obras)
            {
                selectList.Add(new SelectListItem
                {
                    Value = obra.IdObra.ToString(),
                    Text = $"{obra.CodigoObra.PadLeft(3, '0')} - {obra.NomeObra}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarPaises(string codigoOuNome)
        {
            var requisicao = new ListarPaisesRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarPaisesRequisicao, ListarPaisesResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Paises = resultado.Paises.OrderBy("NomePais asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var pais in resultado.Paises)
            {
                selectList.Add(new SelectListItem
                {
                    Value = pais.IdPais.ToString(),
                    Text = $"{pais.CodigoPais.ToString().PadLeft(4, '0')} - {pais.NomePais}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarEstados(string codigoOuNome, string idPais)
        {
            var requisicao = new ListarEstadosPorPaisRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdPais = int.Parse(idPais),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarEstadosPorPaisRequisicao, ListarEstadosPorPaisResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Estados = resultado.Estados.OrderBy("NomeEstado asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var estado in resultado.Estados)
            {
                selectList.Add(new SelectListItem
                {
                    Value = estado.IdEstado.ToString(),
                    Text = $"{estado.SiglaEstado} - {estado.NomeEstado}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarMunicipios(string codigoOuNome, string idEstado)
        {
            var requisicao = new ListarMunicipiosPorEstadoRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdEstado = int.Parse(idEstado),
                CodigoOuNome = codigoOuNome
            };

PR.Building4U/PR.Building4U.WebUI/Views/CadastroFuncionarios/Index.cshtml
@using PR.Building4U.WebUI.Helper
@using PR.Building4U.WebUI.Models

@{ ViewBag.Title = "Cadastro de Funcionários"; }

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tabelaCadastro" class="table table-bordered table-striped dataTable" style="width:100%"></table>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    var botoes = new List<ButtonViewModel>()
    {
        new ButtonViewModel(){ Id = "btnCancelar", Text = "Cancelar", Icon = "fas fa-times", Color = "danger", Classe = "btn-rounded", Click = "cadastroFuncionarios.Cancelar()" },
        new ButtonViewModel(){ Id = "btnSalvar", Text = "Salvar", Icon = "fas fa-check", Color = "info", Classe = "btn-rounded", Click = "cadastroFuncionarios.Salvar()" }
    };

    var botoesDemissao = new List<ButtonViewModel>()
    {
        new ButtonViewModel(){ Id = "btnCancelar", Text = "Cancelar", Icon = "fas fa-times", Color = "danger", Classe = "btn-rounded", Click = "cadastroFuncionarios.CancelarDemissao()" },
        new ButtonViewModel(){ Id = "btnConfirmar", Text = "Confirmar", Icon = "fas fa-check", Color = "info", Classe = "btn-rounded", Click = "cadastroFuncionarios.ConfirmarDemissao()" }
    };
}

@Html.Modal("modalCadastro", "Cadastro de Funcionário", Html.Partial("_Cadastro").ToString(), true, botoes)

@Html.Modal("modalDemissao", "Demissão de Funcionário", Html.Partial("_Demissao").ToString(), true, botoesDemissao)

<script>
    var urlListar = '@Url.Action("Listar", "CadastroFuncionarios", new { Area = "" })';
	var urlIncluir = '@Url.Action("Incluir", "CadastroFuncionarios", new { Area = "" })';
	var urlEditar = '@Url.Action("Editar", "CadastroFuncionarios", new { Area = "" })';
	var urlDemitir = '@Url.Action("Demitir", "CadastroFuncionarios", new { Area = "" })';
    var urlObter = '@Url.Action("Obter", "CadastroFuncionarios", new { Area = "" })';
    var urlListarCargos = '@Url.Action("ListarCargos", "CadastroFuncionarios", new { Area = "" })';
    var urlListarObras = '@Url.Action("ListarObras", "CadastroFuncionarios", new { Area = "" })';
    var urlListarPaises = '@Url.Action("ListarPaises", "CadastroFuncionarios", new { Area = "" })';
    var urlListarEstados = '@Url.Action("ListarEstados", "CadastroFuncionarios", new { Area = "" })';
    var urlListarMunicipios = '@Url.Action("ListarMunicipios", "CadastroFuncionarios", new { Area = "" })';
</script>

PR.Building4U/PR.Building4U.WebUI/Views/CadastroFuncionarios/_Cadastro.cshtml
@using PR.Building4U.WebUI.Helper

<div class="form">
    <div class="row">
        @Html.Hidden("hidIdFuncionario")
        <div class="col-xlg-1 col-lg-2 col-md-3 col-sm-5 col-5">
            @Html.InputNumerico("inpChapaFuncionario", "", true, "Chapa", "", new { @class = "form-control", @maxlength = "7" })
        </div>
        <div class="col-xlg-2 col-lg-3 col-md-4 col-sm-7 col-7">
            @Html.InputData("inpAdmissaoFuncionario", null, true, "Admissão", "", new { @class = "form-control" })
        </div>
        <div class="col-xlg-4 col-lg-9 col-md-12 col-sm-12 col-12">
            @Html.Input("inpNomeFuncionario", "", true, "Nome", "", new { @class = "form-control", @maxlength = "50" })
        </div>
        <div class="col-xlg-4 col-lg-9 col-md-12 col-sm-12 col-12">
            @Html.InputEmail("inpEmailFuncionario", "", false, "Email", "", new { @class = "form-control", @maxlength = "50" })
        </div>
        <div class="col-xlg-2 col-lg-4 col-md-5 col-sm-8 col-8">
            @Html.InputTelefone("inpTelefoneFuncionario", "", false, "Telefone", "", new { @class = "form-control" })
        </div>
        <div class="col-xlg-2 col-lg-5 col-md-7 col-sm-12 col-12">
            @Html.Select("selIdCargo", null, true, "Cargo", new { @class = "form-control select2" })
        </div>
        <div class="col-xlg-2 col-lg-5 col-md-7 col-sm-12 col-12">
            @Html.Select("selIdObra", null, true, "Obra", new { @class = "form-control select2" })
        </div>
    </div>
    <div class="block-title">Endereço:</div>
    <div class="block row">
        @Html.Hidden("hidIdEndereco")
        <div class="col-xlg-4 col-lg-9 col-md-12 col-sm-12 col-12">
            @Html.Input("inpLogradouroEndereco", "", true, "Logradouro", "", new { @class = "form-control", @maxlength = "50" })
        </div>
        <div class="col-xlg-1 col-lg-4 col-md-3 col-sm-4 col-4">
            @Html.Input("inpNumeroEndereco", "", false, "Número", "", new { @class = "form-control", @maxlength = "10" })
        </div>
        <div class="col-xlg-2 col-lg-4 col-md-4 col-sm-8 col-8">
            @Html.InputCep("inpCepEndereco", "", false, "CEP", "", new { @class = "form-control" })
        </div>
        <div class="col-xlg-2 col-lg-4 col-md-6 col-sm-12 col-12">
            @Html.Input("inpComplementoEndereco", "", false, "Complemento", "", new { @class = "form-control", @maxlength = "20" })
        </div>
        <div class="col-xlg-3 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Input("inpDistritoEndereco", "", true, "Bairro/Distrito", "", new { @class = "form-control", @maxlength = "30" })
        </div>
        <div class="col-xlg-3 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Select("selIdPais", null, true, "País", new { @class = "form-control select2" })
        </div>
        <div class="col-xlg-2 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Select("selIdEstado", null, true, "Estado", new { @class = "form-control select2" })
        </div>
        <div class="col-xlg-3 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Select("selIdMunicipio", null, true, "Município", new { @class = "form-control select2" })
        </div>
    </div>
</div>

PR.Building4U/PR.Building4U.WebUI/Views/CadastroFuncionarios/_Demissao.cshtml
@using PR.Building4U.WebUI.Helper

<div class="form">
    <div class="row">
        @Html.Hidden("hidIdFuncionarioDemissao")
        <div class="col-xlg-5 col-lg-5 col-md-5 col-sm-6 col-6">
            @Html.InputData("inpDemissaoFuncionario", null, true, "Data de Demissão", "", new { @class = "form-control" })
        </div>
        <div class="col-xlg-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <h5>Confirma a demissão do funcionário <span id="spnNomeFuncionario"></span>?</h5>
        </div>
    </div>
</div>