PR.Building4U/PR.Building4U.WebUI/Controllers/CadastroCargosController.cs
using PR.Building4U.Fronteiras.Executores.AdministrarCargo;
using PR.Building4U.Fronteiras.Executores.AdministrarCusto;
using PR.Building4U.WebUI.DataAnnotations;
using PR.Building4U.WebUI.Helper;
using PR.Building4U.WebUI.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PR.Building4U.WebUI.Controllers
{
    public class CadastroCargosController : BaseController
    {
        [Authorization]
        public ActionResult Index()
        {
            ViewBag.ListaCustos = ListarCustos();

            return View();
        }

        [Authorization(new[] { "Index" })]
        public ActionResult Listar(DataTableAjaxPostModel model)
        {
            var requisicao = new ListarCargosRequisicao
            {
                InformacoesLog = this.GetInformacoesLog()
            };
            var executor = this.CriarExecutor<ListarCargosRequisicao, ListarCargosResultado>();
            var resultado = executor.Executar(requisicao);

            var datatable = this.RenderDatatableToView(model, resultado.Cargos);

            return Json(datatable, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Incluir(string siglaCargo, string nomeCargo, int idCusto)
        {
            var requisicao = new IncluirCargoRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                SiglaCargo = siglaCargo.ToUpper(),
                NomeCargo = nomeCargo,
                IdCusto = idCusto
            };
            var executor = this.CriarExecutor<IncluirCargoRequisicao, IncluirCargoResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Editar(int idCargo, string siglaCargo, string nomeCargo, int idCusto)
        {
            var requisicao = new EditarCargoRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdCargo = idCargo,
                SiglaCargo = siglaCargo,
                NomeCargo = nomeCargo,
                IdCusto = idCusto
            };
            var executor = this.CriarExecutor<EditarCargoRequisicao, EditarCargoResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Excluir(int idCargo)
        {
            var requisicao = new ExcluirCargoRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdCargo = idCargo
            };
            var executor = this.CriarExecutor<ExcluirCargoRequisicao, ExcluirCargoResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Editar" })]
        public ActionResult Obter(int idCargo)
        {
            var requisicao = new ObterCargoRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdCargo = idCargo
            };
            var executor = this.CriarExecutor<ObterCargoRequisicao, ObterCargoResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        private List<SelectListItem> ListarCustos()
        {
            var requisicao = new ListarCustosRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
            };
            var executor = this.CriarExecutor<ListarCustosRequisicao, ListarCustosResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Custos = resultado.Custos.OrderBy("NomeCusto asc").ToList();

            var selectList = resultado.Custos.Select(x => new SelectListItem
            {
                Text = x.NomeCusto,
                Value = x.IdCusto.ToString()
            }).ToList();

            return selectList;
        }
    }
}

PR.Building4U/PR.Building4U.WebUI/Views/CadastroCargos/Index.cshtml
@using PR.Building4U.WebUI.Helper
@using PR.Building4U.WebUI.Models

@{ ViewBag.Title = "Cadastro de Cargos"; }

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tabelaCadastro" class="table table-bordered table-striped dataTable" style="width:100%"></table>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    var botoes = new List<ButtonViewModel>()
    {
        new ButtonViewModel(){ Id = "btnCancelar", Text = "Cancelar", Icon = "fas fa-times", Color = "danger", Classe = "btn-rounded", Click = "cadastroCargos.Cancelar()" },
		new ButtonViewModel(){ Id = "btnSalvar", Text = "Salvar", Icon = "fas fa-check", Color = "info", Classe = "btn-rounded", Click = "cadastroCargos.Salvar()" }
    };
}

@Html.Modal("modalCadastro", "Cadastro de Cargo", Html.Partial("_Cadastro").ToString(), true, botoes)

<script>
    var urlListar = '@Url.Action("Listar", "CadastroCargos", new { Area = "" })';
	var urlIncluir = '@Url.Action("Incluir", "CadastroCargos", new { Area = "" })';
	var urlEditar = '@Url.Action("Editar", "CadastroCargos", new { Area = "" })';
	var urlExcluir = '@Url.Action("Excluir", "CadastroCargos", new { Area = "" })';
    var urlObter = '@Url.Action("Obter", "CadastroCargos", new { Area = "" })';
    var urlListarCustos = '@Url.Action("ListarCustos", "CadastroCargos", new { Area = "" })';
</script>

PR.Building4U/PR.Building4U.WebUI/Views/CadastroCargos/_Cadastro.cshtml
@using PR.Building4U.WebUI.Helper

<div class="form">
    @Html.Hidden("hidIdCargo")
    <div class="row">
        <div class="col-xlg-3 col-lg-6 col-md-9 col-sm-12 col-12">
            @Html.Input("inpNomeCargo", "", true, "Nome", "", new { @class = "form-control", @maxlength = "30" })
        </div>
        <div class="col-xlg-1 col-lg-3 col-md-4 col-sm-6 col-6">
            @Html.Input("inpSiglaCargo", "", false, "Sigla", "", new { @class = "form-control upper-text", @maxlength = "10" })
        </div>
        <div class="col-xlg-1 col-lg-3 col-md-5 col-sm-6 col-6">
            @Html.Select("selIdCusto", (List<SelectListItem>)ViewBag.ListaCustos, true, "Custo", new { @class = "form-control select2" })
        </div>
    </div>
</div>