PR.Building4U/PR.Building4U.WebUI/Controllers/CadastroClientesController.cs
using PR.Building4U.Fronteiras.Dtos;
using PR.Building4U.Fronteiras.Executores.AdministrarCliente;
using PR.Building4U.Fronteiras.Executores.AdministrarEstado;
using PR.Building4U.Fronteiras.Executores.AdministrarMunicipio;
using PR.Building4U.Fronteiras.Executores.AdministrarPais;
using PR.Building4U.WebUI.DataAnnotations;
using PR.Building4U.WebUI.Helper;
using PR.Building4U.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PR.Building4U.WebUI.Controllers
{
    public class CadastroClientesController : BaseController
    {
        [Authorization]
        public ActionResult Index()
        {
            return View();
        }

        [Authorization(new[] { "Index" })]
        public ActionResult Listar(DataTableAjaxPostModel model)
        {
            var requisicao = new ListarClientesRequisicao
            {
                InformacoesLog = this.GetInformacoesLog()
            };
            var executor = this.CriarExecutor<ListarClientesRequisicao, ListarClientesResultado>();
            var resultado = executor.Executar(requisicao);

            var datatable = this.RenderDatatableToView(model, resultado.Clientes);

            return Json(datatable, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Incluir(ClienteDto cliente)
        {
            var requisicao = new IncluirClienteRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                CnpjCliente = cliente.CnpjCliente,
                RazaoSocialCliente = cliente.RazaoSocialCliente,
                NomeCliente = cliente.NomeCliente,
                LogradouroEndereco = cliente.Endereco.LogradouroEndereco,
                NumeroEndereco = cliente.Endereco.NumeroEndereco,
                ComplementoEndereco = cliente.Endereco.ComplementoEndereco,
                CepEndereco = cliente.Endereco.CepEndereco,
                DistritoEndereco = cliente.Endereco.DistritoEndereco,
                IdMunicipio = cliente.Endereco.Municipio.IdMunicipio
            };
            var executor = this.CriarExecutor<IncluirClienteRequisicao, IncluirClienteResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Editar(ClienteDto cliente)
        {
            var requisicao = new EditarClienteRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdCliente = cliente.IdCliente,
                RazaoSocialCliente = cliente.RazaoSocialCliente,
                NomeCliente = cliente.NomeCliente,
                IdEndereco = cliente.Endereco.IdEndereco,
                LogradouroEndereco = cliente.Endereco.LogradouroEndereco,
                NumeroEndereco = cliente.Endereco.NumeroEndereco,
                ComplementoEndereco = cliente.Endereco.ComplementoEndereco,
                CepEndereco = cliente.Endereco.CepEndereco,
                DistritoEndereco = cliente.Endereco.DistritoEndereco,
                IdMunicipio = cliente.Endereco.Municipio.IdMunicipio
            };
            var executor = this.CriarExecutor<EditarClienteRequisicao, EditarClienteResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Desativar(int idCliente, DateTime dataDesativado)
        {
            var requisicao = new DesativarClienteRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdCliente = idCliente,
                DataDesativado = dataDesativado
            };
            var executor = this.CriarExecutor<DesativarClienteRequisicao, DesativarClienteResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Editar" })]
        public ActionResult Obter(int idCliente)
        {
            var requisicao = new ObterClienteRequisicao()
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdCliente = idCliente
            };
            var executor = this.CriarExecutor<ObterClienteRequisicao, ObterClienteResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarPaises(string codigoOuNome)
        {
            var requisicao = new ListarPaisesRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarPaisesRequisicao, ListarPaisesResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Paises = resultado.Paises.OrderBy("NomePais asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var pais in resultado.Paises)
            {
                selectList.Add(new SelectListItem
                {
                    Value = pais.IdPais.ToString(),
                    Text = $"{pais.CodigoPais.ToString().PadLeft(4, '0')} - {pais.NomePais}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarEstados(string codigoOuNome, string idPais)
        {
            var requisicao = new ListarEstadosPorPaisRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdPais = int.Parse(idPais),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarEstadosPorPaisRequisicao, ListarEstadosPorPaisResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Estados = resultado.Estados.OrderBy("NomeEstado asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var estado in resultado.Estados)
            {
                selectList.Add(new SelectListItem
                {
                    Value = estado.IdEstado.ToString(),
                    Text = $"{estado.SiglaEstado} - {estado.NomeEstado}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarMunicipios(string codigoOuNome, string idEstado)
        {
            var requisicao = new ListarMunicipiosPorEstadoRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdEstado = int.Parse(idEstado),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarMunicipiosPorEstadoRequisicao, ListarMunicipiosPorEstadoResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Municipios = resultado.Municipios.OrderBy("NomeMunicipio asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var municipio in resultado.Municipios)
            {
                selectList.Add(new SelectListItem
                {
                    Value = municipio.IdMunicipio.ToString(),
                    Text = $"{municipio.CodigoMunicipio.ToString().PadLeft(4, '0')} - {municipio.NomeMunicipio}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }
    }
}

PR.Building4U/PR.Building4U.WebUI/Views/CadastroClientes/Index.cshtml
@using PR.Building4U.WebUI.Helper
@using PR.Building4U.WebUI.Models

@{ ViewBag.Title = "Cadastro de Clientes"; }

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tabelaCadastro" class="table table-bordered table-striped dataTable" style="width:100%"></table>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    var botoes = new List<ButtonViewModel>()
    {
        new ButtonViewModel(){ Id = "btnCancelar", Text = "Cancelar", Icon = "fas fa-times", Color = "danger", Classe = "btn-rounded", Click = "cadastroClientes.Cancelar()" },
        new ButtonViewModel(){ Id = "btnSalvar", Text = "Salvar", Icon = "fas fa-check", Color = "info", Classe = "btn-rounded", Click = "cadastroClientes.Salvar()" }
    };

    var botoesDesativar = new List<ButtonViewModel>()
    {
        new ButtonViewModel(){ Id = "btnCancelar", Text = "Cancelar", Icon = "fas fa-times", Color = "danger", Classe = "btn-rounded", Click = "cadastroClientes.CancelarDesativar()" },
        new ButtonViewModel(){ Id = "btnConfirmar", Text = "Confirmar", Icon = "fas fa-check", Color = "info", Classe = "btn-rounded", Click = "cadastroClientes.ConfirmarDesativar()" }
    };
}

@Html.Modal("modalCadastro", "Cadastro de Cliente", Html.Partial("_Cadastro").ToString(), true, botoes)

@Html.Modal("modalDesativar", "Desativar Cliente", Html.Partial("_Desativar").ToString(), true, botoesDesativar)

<script>
    var urlListar = '@Url.Action("Listar", "CadastroClientes", new { Area = "" })';
	var urlIncluir = '@Url.Action("Incluir", "CadastroClientes", new { Area = "" })';
	var urlEditar = '@Url.Action("Editar", "CadastroClientes", new { Area = "" })';
	var urlDesativar = '@Url.Action("Desativar", "CadastroClientes", new { Area = "" })';
    var urlObter = '@Url.Action("Obter", "CadastroClientes", new { Area = "" })';
    var urlListarPaises = '@Url.Action("ListarPaises", "CadastroClientes", new { Area = "" })';
    var urlListarEstados = '@Url.Action("ListarEstados", "CadastroClientes", new { Area = "" })';
    var urlListarMunicipios = '@Url.Action("ListarMunicipios", "CadastroClientes", new { Area = "" })';
</script>

PR.Building4U/PR.Building4U.WebUI/Views/CadastroClientes/_Cadastro.cshtml
@using PR.Building4U.WebUI.Helper
<div class="form">
    <div class="row">
        @Html.Hidden("hidIdCliente")
        <div class="col-xlg-2 col-lg-4 col-md-5 col-sm-10 col-10">
            @Html.InputCpfCnpj("inpCnpjCliente", "", true, "CNPJ/CPF", "", new { @class = "form-control", @maxlength = "18" })
        </div>
        <div class="col-xlg-5 col-lg-12 col-md-12 col-sm-12 col-12">
            @Html.Input("inpRazaoSocialCliente", "", true, "Razão Social", "", new { @class = "form-control", @maxlength = "100" })
        </div>
        <div class="col-xlg-4 col-lg-9 col-md-12 col-sm-12 col-12">
            @Html.Input("inpNomeCliente", "", true, "Nome", "", new { @class = "form-control", @maxlength = "50" })
        </div>
    </div>
    <div class="block-title">Endereço:</div>
    <div class="block row">
        @Html.Hidden("hidIdEndereco")
        <div class="col-xlg-4 col-lg-9 col-md-12 col-sm-12 col-12">
            @Html.Input("inpLogradouroEndereco", "", true, "Logradouro", "", new { @class = "form-control", @maxlength = "50" })
        </div>
        <div class="col-xlg-1 col-lg-4 col-md-3 col-sm-6 col-6">
            @Html.Input("inpNumeroEndereco", "", false, "Número", "", new { @class = "form-control", @maxlength = "10" })
        </div>
        <div class="col-xlg-2 col-lg-4 col-md-4 col-sm-6 col-6">
            @Html.InputCep("inpCepEndereco", "", false, "CEP", "", new { @class = "form-control" })
        </div>
        <div class="col-xlg-2 col-lg-4 col-md-6 col-sm-12 col-12">
            @Html.Input("inpComplementoEndereco", "", false, "Complemento", "", new { @class = "form-control", @maxlength = "20" })
        </div>
        <div class="col-xlg-3 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Input("inpDistritoEndereco", "", true, "Bairro/Distrito", "", new { @class = "form-control", @maxlength = "30" })
        </div>
        <div class="col-xlg-3 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Select("selIdPais", null, true, "País", new { @class = "form-control select2" })
        </div>
        <div class="col-xlg-2 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Select("selIdEstado", null, true, "Estado", new { @class = "form-control select2" })
        </div>
        <div class="col-xlg-3 col-lg-6 col-md-8 col-sm-12 col-12">
            @Html.Select("selIdMunicipio", null, true, "Município", new { @class = "form-control select2" })
        </div>
    </div>
</div>

PR.Building4U/PR.Building4U.WebUI/Views/CadastroClientes/_Desativar.cshtml
@using PR.Building4U.WebUI.Helper

<div class="form">
    <div class="row">
        @Html.Hidden("hidIdClienteDesativar")
        <div class="col-xlg-5 col-lg-5 col-md-5 col-sm-6 col-6">
            @Html.InputData("inpDesativarCliente", null, true, "Data p/ Desativar", "", new { @class = "form-control" })
        </div>
        <div class="col-xlg-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <h5>Confirma desativar o cliente <span id="spnNomeCliente"></span>?</h5>
        </div>
    </div>
</div>