PR.Building4U/PR.Building4U.WebUI/Controllers/CadastroMunicipiosController.cs
using PR.Building4U.Fronteiras.Executores.AdministrarEstado;
using PR.Building4U.Fronteiras.Executores.AdministrarMunicipio;
using PR.Building4U.Fronteiras.Executores.AdministrarPais;
using PR.Building4U.WebUI.DataAnnotations;
using PR.Building4U.WebUI.Helper;
using PR.Building4U.WebUI.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PR.Building4U.WebUI.Controllers
{
    public class CadastroMunicipiosController : BaseController
    {
        [Authorization]
        public ActionResult Index()
        {
            return View();
        }

        [Authorization(new[] { "Index" })]
        public ActionResult Listar(DataTableAjaxPostModel model)
        {
            var requisicao = new ListarMunicipiosRequisicao
            {
                InformacoesLog = this.GetInformacoesLog()
            };
            var executor = this.CriarExecutor<ListarMunicipiosRequisicao, ListarMunicipiosResultado>();
            var resultado = executor.Executar(requisicao);

            var datatable = this.RenderDatatableToView(model, resultado.Municipios);

            return Json(datatable, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Incluir(int codigoMunicipio, string nomeMunicipio, int idEstado)
        {
            var requisicao = new IncluirMunicipioRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                CodigoMunicipio = codigoMunicipio,
                NomeMunicipio = nomeMunicipio,
                IdEstado = idEstado
            };
            var executor = this.CriarExecutor<IncluirMunicipioRequisicao, IncluirMunicipioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Editar(int idMunicipio, int codigoMunicipio, string nomeMunicipio, int idEstado)
        {
            var requisicao = new EditarMunicipioRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdMunicipio = idMunicipio,
                CodigoMunicipio = codigoMunicipio,
                NomeMunicipio = nomeMunicipio,
                IdEstado = idEstado
            };
            var executor = this.CriarExecutor<EditarMunicipioRequisicao, EditarMunicipioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization]
        public ActionResult Excluir(int idMunicipio)
        {
            var requisicao = new ExcluirMunicipioRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdMunicipio = idMunicipio
            };
            var executor = this.CriarExecutor<ExcluirMunicipioRequisicao, ExcluirMunicipioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(new { sucesso = resultado.Sucesso, mensagem = resultado.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Editar" })]
        public ActionResult Obter(int idMunicipio)
        {
            var requisicao = new ObterMunicipioRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdMunicipio = idMunicipio
            };
            var executor = this.CriarExecutor<ObterMunicipioRequisicao, ObterMunicipioResultado>();
            var resultado = executor.Executar(requisicao);

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarPaises(string codigoOuNome)
        {
            var requisicao = new ListarPaisesRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarPaisesRequisicao, ListarPaisesResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Paises = resultado.Paises.OrderBy("NomePais asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var pais in resultado.Paises)
            {
                selectList.Add(new SelectListItem
                {
                    Value = pais.IdPais.ToString(),
                    Text = $"{pais.CodigoPais.ToString().PadLeft(4, '0')} - {pais.NomePais}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }

        [Authorization(new[] { "Incluir", "Editar" })]
        public ActionResult ListarEstados(string codigoOuNome, string idPais)
        {
            var requisicao = new ListarEstadosPorPaisRequisicao
            {
                InformacoesLog = this.GetInformacoesLog(),
                IdPais = int.Parse(idPais),
                CodigoOuNome = codigoOuNome
            };
            var executor = this.CriarExecutor<ListarEstadosPorPaisRequisicao, ListarEstadosPorPaisResultado>();
            var resultado = executor.Executar(requisicao);

            resultado.Estados = resultado.Estados.OrderBy("NomeEstado asc").ToList();

            var selectList = new List<SelectListItem>();

            foreach (var estado in resultado.Estados)
            {
                selectList.Add(new SelectListItem
                {
                    Value = estado.IdEstado.ToString(),
                    Text = $"{estado.SiglaEstado} - {estado.NomeEstado}"
                });
            }

            return Json(selectList, JsonRequestBehavior.AllowGet);
        }
    }
}

PR.Building4U/PR.Building4U.WebUI/Views/CadastroMunicipios/CadastrarMunicipio.cshtml
@model PR.Building4U.Fronteiras.Dtos.MunicipioDto
@using PR.Building4U.WebUI.Helper
@using PR.Building4U.WebUI.Models
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdMunicipio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdMunicipio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdMunicipio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeMunicipio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeMunicipio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeMunicipio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodigoMunicipio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoMunicipio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoMunicipio, "", new { @class = "text-danger" })
            </div>
        </div>


    </div>
}

PR.Building4U/PR.Building4U.WebUI/Views/CadastroMunicipios/Index.cshtml
@using PR.Building4U.WebUI.Helper
@using PR.Building4U.WebUI.Models

@{ ViewBag.Title = "Cadastro de Municípios"; }

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tabelaCadastro" class="table table-bordered table-striped dataTable" style="width:100%"></table>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    var botoes = new List<ButtonViewModel>()
    {
        new ButtonViewModel(){ Id = "btnCancelar", Text = "Cancelar", Icon = "fas fa-times", Color = "danger", Classe = "btn-rounded", Click = "cadastroMunicipios.Cancelar()" },
        new ButtonViewModel(){ Id = "btnSalvar", Text = "Salvar", Icon = "fas fa-check", Color = "info", Classe = "btn-rounded", Click = "cadastroMunicipios.Salvar()" }
    };
}

@Html.Modal("modalCadastro", "Cadastro de Município", Html.Partial("_Cadastro").ToString(), true, botoes)

<script>
    var urlListar = '@Url.Action("Listar", "CadastroMunicipios", new { Area = "" })';
    var urlIncluir = '@Url.Action("Incluir", "CadastroMunicipios", new { Area = "" })';
    var urlEditar = '@Url.Action("Editar", "CadastroMunicipios", new { Area = "" })';
    var urlExcluir = '@Url.Action("Excluir", "CadastroMunicipios", new { Area = "" })';
    var urlObter = '@Url.Action("Obter", "CadastroMunicipios", new { Area = "" })';
    var urlListarEstados = '@Url.Action("ListarEstados", "CadastroMunicipios", new { Area = "" })';
    var urlListarPaises = '@Url.Action("ListarPaises", "CadastroMunicipios", new { Area = "" })';
</script>

PR.Building4U/PR.Building4U.WebUI/Views/CadastroMunicipios/_Cadastro.cshtml
@using PR.Building4U.WebUI.Helper

<div class="form">
    @Html.Hidden("hidIdMunicipio")
    <div class="row">
        <div class="col-xlg-1 col-lg-2 col-md-3 col-sm-4 col-4">
            @Html.InputNumerico("inpCodigoMunicipio", "", true, "Código", "", new { @class = "form-control numerico", @maxlength = "4" })
        </div>
        <div class="col-xlg-4 col-lg-9 col-md-12 col-sm-12 col-12">
            @Html.Input("inpNomeMunicipio", "", true, "Nome", "", new { @class = "form-control", @maxlength = "50" })
        </div>
        <div class="col-xlg-3 col-lg-6 col-md-9 col-sm-12 col-12">
            @Html.Select("selIdPais", null, true, "País", new { @class = "form-control select2" })
        </div>
        <div class="col-xlg-2 col-lg-5 col-md-7 col-sm-12 col-12">
            @Html.Select("selIdEstado", null, true, "Estado", new { @class = "form-control select2" })
        </div>
    </div>
</div>